version: '3.7'

services:
  db:
    image: postgis/postgis
    volumes:
      - postgis_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=JohnCA
      - POSTGRES_DB=djangosqlalchemy
    ports:
      - '5432:5432'
volumes:
  build_folder:
  postgis_data: